/*
 * GENERATED by scripts/ai-model-manifest.mjs. Do not edit by hand: run `npm run ai:manifest`.
 *
 * Every file each chat model is made of, with its size and SHA-256, from Hugging
 * Face and GitHub. A model file imported from the visitor's device is accepted only
 * if every part matches (features/ai/logic/model-file.ts).
 */

export interface ManifestFile {
  url: string;
  size: number;
  sha256: string;
}

export const modelManifest: Record<string, readonly ManifestFile[]> = {
  "Qwen2.5-0.5B-Instruct-q4f16_1-MLC": [
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/merges.txt",
      "size": 1671839,
      "sha256": "599bab54075088774b1733fde865d5bd747cbcc7a547c5bc12610e874e26f5e3"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/mlc-chat-config.json",
      "size": 2041,
      "sha256": "5439c03bdf4ee7cfe0f8a97a6588018b0144dc1280c71bbaea2853cdbab874b9"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/ndarray-cache.json",
      "size": 102431,
      "sha256": "23a54b5e9b271204561901b513c5b359498733429ee219ccc907eb1cd0790e3f"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_0.bin",
      "size": 68067328,
      "sha256": "9f309954d310dc63adfaf3ef6aa987c681b8aa6d1b9686aa2525b454b0d058d5"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_1.bin",
      "size": 33234176,
      "sha256": "6d174758dd299d9ef4222b1ad4283be832ebd43853951da25b50501ab1b75ba7"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_2.bin",
      "size": 33505280,
      "sha256": "83e0b530bf5c44cbead1a6c220af81040a975f7c81fb708977a02e3ac8d7ffa7"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_3.bin",
      "size": 33053696,
      "sha256": "5ff16197c197d8783d398d0c35fa9641e606e6e2dc1d53b9f26a0c9c17a97921"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_4.bin",
      "size": 33020928,
      "sha256": "a7a3d2b02aa9258154f250a714d1743672e423c5c7c8e5c5eefcb9bf337aa0fd"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_5.bin",
      "size": 29211648,
      "sha256": "19dfd7a3064b84082915575c0e5a57fc1cd7108828e1ce9fbbbaf9db4b63b9af"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_6.bin",
      "size": 33297408,
      "sha256": "192576d43956aa977ec60848b8a7fc8483b5fe38ca9669aa9a3ca2ba795a7a33"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_7.bin",
      "size": 14605824,
      "sha256": "1ee25c2a41dad6833e000b7e3ec13a5a1761c32ffbed0ad8a98a6ad313338dc0"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/tensor-cache.json",
      "size": 102431,
      "sha256": "23a54b5e9b271204561901b513c5b359498733429ee219ccc907eb1cd0790e3f"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/tokenizer_config.json",
      "size": 7308,
      "sha256": "5214600ee45ca2f887ce2eede8910378a0111ea99d657428bcbce94778e65a92"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/tokenizer.json",
      "size": 7031645,
      "sha256": "c0382117ea329cdf097041132f6d735924b697924d6f6fc3945713e96ce87539"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/resolve/main/vocab.json",
      "size": 2776833,
      "sha256": "ca10d7e9fb3ed18575dd1e277a2579c16d108e32f27439684afa0e10b1440910"
    },
    {
      "url": "https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/web-llm-models/v0_2_84/base/Qwen2-0.5B-Instruct-q4f16_1_cs1k-webgpu.wasm",
      "size": 4850160,
      "sha256": "611b584fd44af2789416395603965a6bc074f2127188af597f4dda016fbdab19"
    }
  ],
  "SmolLM2-360M-Instruct-q4f32_1-MLC": [
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/merges.txt",
      "size": 466391,
      "sha256": "0b54e8aa4e53d5383e2e4bc635a56b43f9647f7b13832d5d9ecd8f82dac4f510"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/mlc-chat-config.json",
      "size": 2021,
      "sha256": "0c12f5b060239daedd1304cafff19cc2ce0d3e819359c85561394d16049244e6"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/ndarray-cache-b16.json",
      "size": 122872,
      "sha256": "f9421383b221df0fb55a2b7f48e7c19e9f73231c221cfd13cb7eb66f3a0a8213"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/ndarray-cache.json",
      "size": 124230,
      "sha256": "82bbb6b94d83a699a1f530ddee0831a551ef14aaa85b7b1f9e8676169ccdadc9"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/params_shard_0.bin",
      "size": 33459840,
      "sha256": "65a16852a3537d8690e2145a5d438e8bbca53f6a5d367ee38bb5ace215910a2e"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/params_shard_1.bin",
      "size": 33200640,
      "sha256": "212c7c931a324fa02c9c60f295e0ea523c8256e2daf99bcf983237fe3294fdbe"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/params_shard_2.bin",
      "size": 33200640,
      "sha256": "f24d3b8e58c26719bd9d951dc60907f6bede7c39d15c2b0e9479238fa8f2a1aa"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/params_shard_3.bin",
      "size": 33200640,
      "sha256": "cb80fe8b1e636da1b5097fbc4c782f7fb40c7ad5b705c09463cdbf1c110a0342"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/params_shard_4.bin",
      "size": 33200640,
      "sha256": "86807f710055b7d98fe3f4ab66a1d65e2d3d675556705b27c4f7b0b56ced02b2"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/params_shard_5.bin",
      "size": 33200640,
      "sha256": "f706cd8d4096d7bce669f8f8e508a530f101848b3daa6052a62c5942d66cab48"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/params_shard_6.bin",
      "size": 4151040,
      "sha256": "4c8666de839e1de48bc7b1344985a230d8904b03def1bdcc722595ce7449aad0"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/tensor-cache.json",
      "size": 124230,
      "sha256": "82bbb6b94d83a699a1f530ddee0831a551ef14aaa85b7b1f9e8676169ccdadc9"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/tokenizer_config.json",
      "size": 3764,
      "sha256": "a27f638bd2831f5c3dea654a75838930f2b11fbe550c4d4e1d5d7bd07157b2ee"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/tokenizer.json",
      "size": 2104556,
      "sha256": "9ca9acddb6525a194ec8ac7a87f24fbba7232a9a15ffa1af0c1224fcd888e47c"
    },
    {
      "url": "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f32_1-MLC/resolve/main/vocab.json",
      "size": 800662,
      "sha256": "82b84012e3add4d01d12ba14442026e49b8cbbaead1f79ecf3d919784f82dc79"
    },
    {
      "url": "https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/web-llm-models/v0_2_84/base/SmolLM2-360M-Instruct-q4f32_1_cs1k-webgpu.wasm",
      "size": 5679428,
      "sha256": "64d0c417a2154906c18e5d25392a2538e1bcd4ca67f5374782b467da23a29667"
    }
  ],
  "Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC": [
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/merges.txt",
      "size": 1671839,
      "sha256": "599bab54075088774b1733fde865d5bd747cbcc7a547c5bc12610e874e26f5e3"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/mlc-chat-config.json",
      "size": 2043,
      "sha256": "e1ac4f8e323fb7455629cf31aa3021e76f4399657a18ae8936233bf35b2657a1"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/ndarray-cache.json",
      "size": 102431,
      "sha256": "308ae05f2aa75c0fa04a5b822b373af8910548ea9f5c9102750fe010c3845bc6"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_0.bin",
      "size": 68067328,
      "sha256": "8ba207c8b5b2502d9d178202d44dfd774050b79e4abd263faaf1c37084f9e781"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_1.bin",
      "size": 33234176,
      "sha256": "4d65d9746fee0cec58dc28350391f96da2e11c143058237d6149b0229ca5f73b"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_2.bin",
      "size": 33505280,
      "sha256": "fdaaecfaf16fe3cb86840a0fe3c70424b4efc087604e4551dfd1d84b93aee20f"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_3.bin",
      "size": 33053696,
      "sha256": "4b5566be1d7d5a885b92b7d0fa250a6e48db7aa6749a5d8ae32b41e461d34f7e"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_4.bin",
      "size": 33020928,
      "sha256": "c269ed538f402a94b2e7a4f883c20b7764b114ed98ad982df6d59380158ed45a"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_5.bin",
      "size": 29211648,
      "sha256": "4e1fa63b515392f4ca61d44eec16c22fd433862e7e0682f2fc2cc3f0e6c09f0b"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_6.bin",
      "size": 33297408,
      "sha256": "6fd596e81fc46ee295af587f6304adc4f8007d2c826b657df02d6116bd2aab28"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/params_shard_7.bin",
      "size": 14605824,
      "sha256": "a5c04a0de382276122c49db421768b950783f371b321560602b416b44e0152c4"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/tensor-cache.json",
      "size": 102431,
      "sha256": "308ae05f2aa75c0fa04a5b822b373af8910548ea9f5c9102750fe010c3845bc6"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/tokenizer_config.json",
      "size": 7305,
      "sha256": "5b5d4f65d0acd3b2d56a35b56d374a36cbc1c8fa5cf3b3febbbfabf22f359583"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/tokenizer.json",
      "size": 7031645,
      "sha256": "c0382117ea329cdf097041132f6d735924b697924d6f6fc3945713e96ce87539"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC/resolve/main/vocab.json",
      "size": 2776833,
      "sha256": "ca10d7e9fb3ed18575dd1e277a2579c16d108e32f27439684afa0e10b1440910"
    },
    {
      "url": "https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/web-llm-models/v0_2_84/base/Qwen2-0.5B-Instruct-q4f16_1_cs1k-webgpu.wasm",
      "size": 4850160,
      "sha256": "611b584fd44af2789416395603965a6bc074f2127188af597f4dda016fbdab19"
    }
  ],
  "Qwen3-0.6B-q4f16_1-MLC": [
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/merges.txt",
      "size": 1671853,
      "sha256": "8831e4f1a044471340f7c0a83d7bd71306a5b867e95fd870f74d0c5308a904d5"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/mlc-chat-config.json",
      "size": 2075,
      "sha256": "190a51c56b9a07a8d8721266f8e459bcd1b1689bcdff294795cd2bffa203ff2d"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/ndarray-cache.json",
      "size": 129391,
      "sha256": "f4647d617dc869d91fbd7851c65af0a2cf7dd615884ebe3b110013801b65d8c7"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/params_shard_0.bin",
      "size": 77791232,
      "sha256": "61062e64b475309e648516c853c7bd949344f1ce5c0921e9b121f905953ce9e3"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/params_shard_1.bin",
      "size": 32740608,
      "sha256": "a7d9e88e510636b34c850bf19c660c38cdacbe64bd128c6bb4dcc710455db81d"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/params_shard_2.bin",
      "size": 31866624,
      "sha256": "eb5af136518c33abd7c2eb66e154b5504ce27f62728aafffd8fca26a3cab64a9"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/params_shard_3.bin",
      "size": 33505024,
      "sha256": "482d32bfefe36ec9ee452d88c25cce42f31d8350e4abccc8f4727e4006ab2859"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/params_shard_4.bin",
      "size": 32000000,
      "sha256": "b3d1ecb2553ae323c95b19e231dc74e1ef34d63094ccf0dd3e79a37f312663f3"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/params_shard_5.bin",
      "size": 31866624,
      "sha256": "2c753a811fbea6e0292caf39d9f9ceeb8cb5ff74a183f7350be3f846f3013438"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/params_shard_6.bin",
      "size": 33505024,
      "sha256": "52d543cee1e1d6526dae4a5a36a69c1bafa222d1e3e95c4ee46456d56f1aeab2"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/params_shard_7.bin",
      "size": 32000000,
      "sha256": "3d9047c2603d24b4ca8e689bc924a7715224205ba591504238ff5910e8542c65"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/params_shard_8.bin",
      "size": 30097152,
      "sha256": "13985d7899bf0188ff5a0d37fe6254a8b3e3bf7e4aba0d198de1469faa9ef9b4"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/tensor-cache.json",
      "size": 129391,
      "sha256": "f4647d617dc869d91fbd7851c65af0a2cf7dd615884ebe3b110013801b65d8c7"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/tokenizer_config.json",
      "size": 9676,
      "sha256": "bbc2c089e3bef8753f63348c10595767be8998bc6ca7c7ebcaada346d401fba8"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/tokenizer.json",
      "size": 11422654,
      "sha256": "aeb13307a71acd8fe81861d94ad54ab689df773318809eed3cbe794b4492dae4"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC/resolve/main/vocab.json",
      "size": 2776833,
      "sha256": "ca10d7e9fb3ed18575dd1e277a2579c16d108e32f27439684afa0e10b1440910"
    },
    {
      "url": "https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/web-llm-models/v0_2_84/base/Qwen3-0.6B-q4f16_1_cs1k-webgpu.wasm",
      "size": 5535989,
      "sha256": "4db800b24119204e1a0386e8a12e084d5012aa60f77c5bffad362f20498df912"
    }
  ],
  "Qwen3.5-0.8B-q4f16_1-MLC": [
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/merges.txt",
      "size": 3353259,
      "sha256": "a9d356d7bdf1ef4949e3e748e95b8e10ad9d4e2e838eddc38a0a7b6b94d1db8d"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/mlc-chat-config.json",
      "size": 2358,
      "sha256": "1ea93c2b8b396a3754516d0c4b6f4b6881c2930ca2cc6cb2cf00e511e6be86a9"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_0.bin",
      "size": 127139840,
      "sha256": "414681bc0134320f15d4591521588dd88ae97e6e6a92242a1c2900d6548e99f5"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_1.bin",
      "size": 33193984,
      "sha256": "f23ba01d17f1eaee9f557f48b65bbba80a272e522e96076052037139e58bcce1"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_10.bin",
      "size": 3688064,
      "sha256": "97d2931620ee85c76d2520cec5dab1a56c4061680aae1d46dd52608296211314"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_2.bin",
      "size": 32243712,
      "sha256": "98cf1af3ce6740e1ef8dd9a0148c767c3b0e831e59d140bfada52afa57bb4184"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_3.bin",
      "size": 31850496,
      "sha256": "c76000a164a9893f81ff678bf80a90bcba6d00a450f81a7a52f1c1804b99bde4"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_4.bin",
      "size": 33030144,
      "sha256": "0079356e628317d9bf5d63a297b06c4240470edbb6caa3dbf49daceedeeecf72"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_5.bin",
      "size": 33030144,
      "sha256": "55391999df3b47f96cffe523783092ca3981a088fe1f4602b4270156f8975d3f"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_6.bin",
      "size": 30965760,
      "sha256": "44ec47561a8b0e71569fcb6c3995bea48257b6e1f64f838d0e42b7d06953b44b"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_7.bin",
      "size": 33030144,
      "sha256": "3e299baff5304ad5a7c767a4f8048e850d3cd4d8afc99e86e4daf64708c81ba5"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_8.bin",
      "size": 32735232,
      "sha256": "944ef481f34d54251c7b8408a1ea319a74982abef4535361ecaf7c20bbda228f"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/params_shard_9.bin",
      "size": 33030144,
      "sha256": "4913895152c4d17032eca8f7dbbd7adc8324802ec99db4d41eb7c98a5cadf706"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/tensor-cache-b16.json",
      "size": 167260,
      "sha256": "abc20b8abfe0234c4b96b127e82e78d35432233143db430431f51fce544c75ca"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/tensor-cache.json",
      "size": 167512,
      "sha256": "bab74fa529512ca7641f6a4aea0baeab26742d28886e79aac11b09fa8738c0df"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/tokenizer_config.json",
      "size": 16709,
      "sha256": "49e2b6e395f959f077f1e992b338919c0d4a9732fc6e613995e06557f843500c"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/tokenizer.json",
      "size": 12807982,
      "sha256": "5f9e4d4901a92b997e463c1f46055088b6cca5ca61a6522d1b9f64c4bb81cb42"
    },
    {
      "url": "https://huggingface.co/mlc-ai/Qwen3.5-0.8B-q4f16_1-MLC/resolve/main/vocab.json",
      "size": 6722759,
      "sha256": "ce99b4cb2983d118806ce0a8b777a35b093e2000a503ebde25853284c9dfa003"
    },
    {
      "url": "https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/web-llm-models/v0_2_84/base/Qwen3.5-0.8B-q4f16_1_cs1k-webgpu.wasm",
      "size": 6197129,
      "sha256": "3dd8cff049bf4599bfbb505880aea11ba95f85f3924b7e171f967d1f1348ae29"
    }
  ]
};
