/**
 * Makes the private AI chat page open without the internet.
 *
 * Writes `out/tools/private-ai-chat/sw.js`, a service worker whose scope is that one
 * page, so nothing else on the site is affected. The chat registers it only once a
 * model has been downloaded, because then the visitor has already chosen to use the
 * chat and has fetched its code; a visitor who never uses the chat never gets it.
 *
 * What it keeps: the page itself and every file under `/_next/static/` (the site's
 * scripts, styles and fonts, including the 6 MB WebLLM library and the model worker).
 * Those files have content hashes in their names, so a cached copy is never stale.
 * The model is not its concern: WebLLM keeps it in its own browser caches.
 *
 * How it answers:
 * - the page: network first, so an online visitor always gets the latest; the saved
 *   copy when offline;
 * - `/_next/static/*`: the saved copy, falling back to the network;
 * - anything else (other pages, Hugging Face, GitHub): untouched.
 *
 * The cache name carries a hash of the file list, so each deploy installs a fresh
 * copy and deletes the previous one.
 */

import { createHash } from "node:crypto";
import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";

export const CHAT_PAGE = "tools/private-ai-chat";
export const CACHE_PREFIX = "ef-chat-offline-";

async function* files(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) yield* files(path);
    else yield path;
  }
}

export async function writeChatServiceWorker(outDir) {
  const pageFile = join(outDir, CHAT_PAGE, "index.html");
  const html = await readFile(pageFile, "utf8");
  // The base path the export was built for, read from where the page loads its scripts.
  const match = /(?:src|href)="([^"]*?)\/_next\/static\//.exec(html);
  if (!match) throw new Error(`${CHAT_PAGE}: could not find the page's scripts`);
  const basePath = match[1];

  const assets = [];
  let bytes = 0;
  for await (const file of files(join(outDir, "_next", "static"))) {
    if (file.endsWith(".map")) continue; // debugging aids, never requested by a page
    assets.push(`${basePath}/${relative(outDir, file).split(sep).join("/")}`);
    bytes += (await stat(file)).size;
  }
  assets.sort();
  const page = `${basePath}/${CHAT_PAGE}/`;
  const version = createHash("sha256").update(html).update(assets.join("\n")).digest("hex").slice(0, 12);

  const sw = `// GENERATED by scripts/offline-chat.mjs at build time. Keeps the private AI chat page
// working offline. Scope: ${page} only.
const CACHE = ${JSON.stringify(CACHE_PREFIX + version)};
const PAGE = ${JSON.stringify(page)};
const ASSETS = ${JSON.stringify(assets)};
const STATIC = ${JSON.stringify(`${basePath}/_next/static/`)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll([PAGE, ...ASSETS])).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(${JSON.stringify(CACHE_PREFIX)}) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("message", (event) => {
  if (event.data === "offline-status") {
    caches.open(CACHE).then(async (cache) => {
      const ready = !!(await cache.match(PAGE));
      event.source?.postMessage({ type: "offline-status", ready });
    });
  }
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate" && (url.pathname === PAGE || url.pathname === PAGE + "index.html")) {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(PAGE, copy));
          }
          return response;
        })
        .catch(() => caches.match(PAGE, { cacheName: CACHE }).then((cached) => cached || Response.error())),
    );
    return;
  }

  if (url.pathname.startsWith(STATIC)) {
    event.respondWith(
      caches
        .match(url.pathname, { cacheName: CACHE, ignoreSearch: true })
        .then((cached) => cached || fetch(request)),
    );
  }
});
`;

  await writeFile(join(outDir, CHAT_PAGE, "sw.js"), sw, "utf8");
  return { files: assets.length + 1, megabytes: bytes / 1e6, version };
}
