/*
 * GENERATED by scripts/sync-tools-catalog.mjs from the tools site's tools.json.
 * Do not edit by hand: run `npm run sync:tools`. Validated by config/tools-site.ts.
 */

export const toolsSiteCatalog: unknown = {
  "version": 1,
  "name": "Everything.Free Tools",
  "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/",
  "categories": [
    {
      "slug": "image",
      "name": "Image",
      "tagline": "Resize & convert",
      "description": "Compress, resize, crop and convert pictures.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/image/",
      "toolCount": 4
    },
    {
      "slug": "text",
      "name": "Text",
      "tagline": "Transform & analyse",
      "description": "Count, clean up and transform text.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/text/",
      "toolCount": 10
    },
    {
      "slug": "developer",
      "name": "Developer",
      "tagline": "Build & debug",
      "description": "Formatters, encoders and generators for everyday development.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/developer/",
      "toolCount": 30
    },
    {
      "slug": "data",
      "name": "Data",
      "tagline": "Convert & validate",
      "description": "Validate and convert JSON, CSV and other formats.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/data/",
      "toolCount": 13
    },
    {
      "slug": "files",
      "name": "Files",
      "tagline": "Inspect & fingerprint",
      "description": "Inspect and fingerprint files.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/files/",
      "toolCount": 2
    },
    {
      "slug": "security",
      "name": "Security",
      "tagline": "Hash & generate",
      "description": "Hashes, passwords and random identifiers, explained plainly.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/security/",
      "toolCount": 4
    },
    {
      "slug": "qr-barcode",
      "name": "QR & Barcode",
      "tagline": "Create codes",
      "description": "Create QR codes for links, text and Wi-Fi networks.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/qr-barcode/",
      "toolCount": 1
    },
    {
      "slug": "math",
      "name": "Math",
      "tagline": "Calculate & convert",
      "description": "Calculators and number tools.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/math/",
      "toolCount": 2
    },
    {
      "slug": "color-design",
      "name": "Color & Design",
      "tagline": "Pick & convert",
      "description": "Colour conversion and design helpers.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/color-design/",
      "toolCount": 1
    },
    {
      "slug": "education",
      "name": "Education",
      "tagline": "Learn & study",
      "description": "Tools for learning and study.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/education/",
      "toolCount": 1
    },
    {
      "slug": "everyday",
      "name": "Everyday",
      "tagline": "Small daily jobs",
      "description": "Small jobs that come up all the time.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/categories/everyday/",
      "toolCount": 6
    }
  ],
  "tools": [
    {
      "slug": "api-mock",
      "name": "API Mock & Client Code Generator",
      "description": "Design mock API endpoints and generate cURL, Fetch, Python, and TypeScript snippets.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/api-mock/",
      "category": "developer",
      "alsoIn": [
        "data"
      ],
      "processing": "local",
      "formats": [
        "json"
      ],
      "tags": [
        "api",
        "mock",
        "curl",
        "fetch",
        "client",
        "developer",
        "typescript",
        "python",
        "generator",
        "rest"
      ]
    },
    {
      "slug": "base64",
      "name": "Base64 Encoder / Decoder",
      "description": "Encode text or files to Base64, and decode Base64 back to text or a file.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/base64/",
      "category": "developer",
      "alsoIn": [
        "data"
      ],
      "processing": "local",
      "formats": [
        "txt",
        "b64"
      ],
      "tags": [
        "base64",
        "encoder",
        "decoder",
        "binary",
        "b64",
        "url safe",
        "rfc 4648",
        "data uri"
      ]
    },
    {
      "slug": "case-converter",
      "name": "Case Converter",
      "description": "Transform text between camelCase, snake_case, kebab-case, UPPERCASE, and more.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/case-converter/",
      "category": "text",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "case",
        "camelcase",
        "snake_case",
        "kebab-case",
        "text",
        "developer",
        "uppercase",
        "lowercase",
        "pascalcase"
      ]
    },
    {
      "slug": "color-picker",
      "name": "Color Picker & Converter",
      "description": "Pick colors, convert HEX, RGB, HSL and evaluate contrast ratios.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/color-picker/",
      "category": "color-design",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "css",
        "hex",
        "rgb"
      ],
      "tags": [
        "color",
        "picker",
        "hex",
        "rgb",
        "hsl",
        "contrast",
        "wcag",
        "palette",
        "eyedropper",
        "css color"
      ]
    },
    {
      "slug": "cron-parser",
      "name": "Cron Expression Parser",
      "description": "Parse, explain, and calculate upcoming execution times for cron schedules.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/cron-parser/",
      "category": "developer",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "cron",
        "schedule",
        "parser",
        "crontab",
        "time",
        "job",
        "expression",
        "timer"
      ]
    },
    {
      "slug": "csv-json",
      "name": "CSV ↔ JSON Converter",
      "description": "Convert tabular CSV data to JSON objects and arrays bidirectionally.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/csv-json/",
      "category": "data",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "csv",
        "json"
      ],
      "tags": [
        "csv",
        "json",
        "convert",
        "csv-to-json",
        "spreadsheet",
        "csv to json",
        "json to csv",
        "table",
        "excel"
      ]
    },
    {
      "slug": "csv-viewer",
      "name": "CSV Viewer & Table Explorer",
      "description": "Open, view, search, and sort CSV and TSV files in an interactive table.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/csv-viewer/",
      "category": "data",
      "alsoIn": [
        "files"
      ],
      "processing": "local",
      "formats": [
        "csv",
        "tsv"
      ],
      "tags": [
        "csv",
        "viewer",
        "table",
        "spreadsheet",
        "tsv",
        "explorer",
        "columns"
      ]
    },
    {
      "slug": "find-replace",
      "name": "Find & Replace Text",
      "description": "Batch find and replace text with plain text and regular expression modes.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/find-replace/",
      "category": "text",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "find-replace",
        "search",
        "replace",
        "text",
        "regex",
        "find and replace",
        "search replace",
        "substitute",
        "regex replace",
        "text edit"
      ]
    },
    {
      "slug": "hash-generator",
      "name": "Hash Generator",
      "description": "Compute SHA-256, SHA-512, SHA-1 and MD5 hashes for text and files.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/hash-generator/",
      "category": "security",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "txt",
        "hash"
      ],
      "tags": [
        "hash",
        "sha256",
        "sha512",
        "md5",
        "checksum",
        "sha1",
        "sha384",
        "digest",
        "crypto"
      ]
    },
    {
      "slug": "html-formatter",
      "name": "HTML Formatter & Minifier",
      "description": "Beautify, indent, and minify HTML markup with void element protection.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/html-formatter/",
      "category": "developer",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "html"
      ],
      "tags": [
        "html",
        "formatter",
        "beautifier",
        "minify",
        "web",
        "beautify",
        "indent",
        "cleaner",
        "markup"
      ]
    },
    {
      "slug": "html-preview",
      "name": "HTML Sandboxed Preview",
      "description": "Safely preview HTML, CSS, and JS markup in an isolated browser sandbox.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/html-preview/",
      "category": "developer",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "html"
      ],
      "tags": [
        "html",
        "preview",
        "sandbox",
        "playground",
        "web",
        "render",
        "viewer",
        "iframe"
      ]
    },
    {
      "slug": "http-status",
      "name": "HTTP Status Code Reference",
      "description": "Quickly look up HTTP status codes (1xx–5xx) with RFC specifications and tips.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/http-status/",
      "category": "developer",
      "alsoIn": [
        "everyday"
      ],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "http",
        "status-code",
        "rfc",
        "developer",
        "api",
        "status code",
        "404",
        "500",
        "200",
        "429",
        "rest"
      ]
    },
    {
      "slug": "image-compressor",
      "name": "Image Compressor",
      "description": "Make JPEG, PNG and WebP images smaller, in your browser.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/image-compressor/",
      "category": "image",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "jpeg",
        "png",
        "webp",
        "avif"
      ],
      "tags": [
        "image",
        "compressor",
        "optimize",
        "shrink",
        "image compressor",
        "jpeg",
        "jpg",
        "png",
        "webp",
        "photo",
        "picture",
        "file size"
      ]
    },
    {
      "slug": "image-crop",
      "name": "Image Cropper",
      "description": "Crop images with custom aspect ratio presets and visual selection.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/image-crop/",
      "category": "image",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "png",
        "jpeg",
        "webp"
      ],
      "tags": [
        "image",
        "crop",
        "aspect-ratio",
        "cut photo",
        "image crop",
        "aspect ratio",
        "square",
        "widescreen",
        "photo editor"
      ]
    },
    {
      "slug": "image-format",
      "name": "Image Format Converter",
      "description": "Convert images between PNG, JPEG and WebP formats without uploading.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/image-format/",
      "category": "image",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "png",
        "jpeg",
        "webp"
      ],
      "tags": [
        "image",
        "convert",
        "png-to-jpg",
        "jpg-to-png",
        "webp",
        "image format",
        "converter",
        "png to jpg",
        "jpg to webp",
        "webp converter",
        "transcode",
        "picture"
      ]
    },
    {
      "slug": "image-resize",
      "name": "Image Resizer",
      "description": "Resize images to custom width, height or percentage in your browser.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/image-resize/",
      "category": "image",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "png",
        "jpeg",
        "webp"
      ],
      "tags": [
        "image",
        "resize",
        "scale",
        "dimensions",
        "pixels",
        "image resize",
        "scale photo",
        "resolution",
        "width",
        "height",
        "aspect ratio"
      ]
    },
    {
      "slug": "json-yaml",
      "name": "JSON ↔ YAML Converter",
      "description": "Convert between JSON and YAML formats bidirectionally without uploading.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/json-yaml/",
      "category": "data",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "json",
        "yaml"
      ],
      "tags": [
        "json",
        "yaml",
        "converter",
        "data",
        "configuration",
        "convert",
        "yml",
        "parser"
      ]
    },
    {
      "slug": "json-formatter",
      "name": "JSON Formatter",
      "description": "Format, validate and minify JSON, with the exact location of any error.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/json-formatter/",
      "category": "developer",
      "alsoIn": [
        "data"
      ],
      "processing": "local",
      "formats": [
        "json"
      ],
      "tags": [
        "json",
        "pretty-print",
        "minify",
        "developer",
        "formatter",
        "prettify",
        "beautifier",
        "validator",
        "linter",
        "minifier",
        "indent"
      ]
    },
    {
      "slug": "json-repair",
      "name": "JSON Repair",
      "description": "Fix common JSON syntax errors like unquoted keys and trailing commas.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/json-repair/",
      "category": "developer",
      "alsoIn": [
        "data"
      ],
      "processing": "local",
      "formats": [
        "json"
      ],
      "tags": [
        "json",
        "repair",
        "fix-json",
        "validator",
        "linter",
        "json repair",
        "fix json",
        "invalid json",
        "trailing comma",
        "unquoted keys",
        "single quotes"
      ]
    },
    {
      "slug": "json-schema",
      "name": "JSON Schema Generator",
      "description": "Infer Draft-07 JSON Schema models from sample JSON documents.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/json-schema/",
      "category": "data",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "json"
      ],
      "tags": [
        "json",
        "schema",
        "json-schema",
        "types",
        "draft-07",
        "json schema",
        "schema generator",
        "validator",
        "model"
      ]
    },
    {
      "slug": "json-path",
      "name": "JSONPath Tester",
      "description": "Evaluate JSONPath expressions against JSON documents instantly and locally.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/json-path/",
      "category": "data",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "json"
      ],
      "tags": [
        "json",
        "jsonpath",
        "query",
        "developer",
        "filter",
        "slice",
        "evaluator",
        "tester",
        "extract"
      ]
    },
    {
      "slug": "jwt-debugger",
      "name": "JWT Decoder & Inspector",
      "description": "Decode and inspect JSON Web Token headers, claims, and expiry dates locally.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/jwt-debugger/",
      "category": "security",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "jwt"
      ],
      "tags": [
        "jwt",
        "token",
        "decoder",
        "auth",
        "security",
        "claims",
        "decode",
        "bearer",
        "expiry",
        "json web token"
      ]
    },
    {
      "slug": "markdown-preview",
      "name": "Markdown Preview & Editor",
      "description": "Write and preview Markdown with real-time safe HTML rendering.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/markdown-preview/",
      "category": "developer",
      "alsoIn": [
        "text"
      ],
      "processing": "local",
      "formats": [
        "markdown",
        "html"
      ],
      "tags": [
        "markdown",
        "preview",
        "gfm",
        "editor",
        "html",
        "md",
        "viewer"
      ]
    },
    {
      "slug": "mime-lookup",
      "name": "MIME Type & Extension Lookup",
      "description": "Search file extensions and MIME content types instantly with zero network requests.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/mime-lookup/",
      "category": "developer",
      "alsoIn": [
        "files"
      ],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "mime",
        "content-type",
        "file-extension",
        "lookup",
        "developer",
        "extension",
        "file type",
        "media type"
      ]
    },
    {
      "slug": "number-base",
      "name": "Number Base Converter",
      "description": "Convert numbers between binary, octal, decimal, hexadecimal, and bases 2–36.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/number-base/",
      "category": "math",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "binary",
        "hex",
        "decimal",
        "octal",
        "base-converter",
        "math",
        "base16",
        "base2",
        "radix",
        "converter"
      ]
    },
    {
      "slug": "password-generator",
      "name": "Password Generator",
      "description": "Generate strong, cryptographically secure passwords and passphrases.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/password-generator/",
      "category": "security",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "txt"
      ],
      "tags": [
        "password",
        "passphrase",
        "security",
        "crypto",
        "random",
        "random password",
        "entropy",
        "generator",
        "credentials"
      ]
    },
    {
      "slug": "qr-generator",
      "name": "QR Code Generator",
      "description": "Create QR codes for links, text or Wi-Fi networks, as PNG or SVG.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/qr-generator/",
      "category": "qr-barcode",
      "alsoIn": [
        "everyday"
      ],
      "processing": "local",
      "formats": [
        "png",
        "svg"
      ],
      "tags": [
        "qr",
        "wifi",
        "barcode",
        "svg",
        "qr code",
        "wi fi",
        "link",
        "url",
        "png"
      ]
    },
    {
      "slug": "regex-tester",
      "name": "Regex Tester & Explainer",
      "description": "Test regular expressions with match highlights, capture groups, and structure breakdown.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/regex-tester/",
      "category": "developer",
      "alsoIn": [
        "text"
      ],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "regex",
        "regexp",
        "regular expression",
        "tester",
        "pattern",
        "matcher",
        "capture groups",
        "replace"
      ]
    },
    {
      "slug": "sql-formatter",
      "name": "SQL Formatter & Minifier",
      "description": "Format, beautify and minify SQL queries across multiple database dialects.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/sql-formatter/",
      "category": "developer",
      "alsoIn": [
        "data"
      ],
      "processing": "local",
      "formats": [
        "sql"
      ],
      "tags": [
        "sql",
        "formatter",
        "beautifier",
        "database",
        "query",
        "minify",
        "postgres",
        "mysql"
      ]
    },
    {
      "slug": "table-generator",
      "name": "Table Generator",
      "description": "Generate Markdown and HTML tables from CSV or tabular data.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/table-generator/",
      "category": "data",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "csv",
        "json"
      ],
      "tags": [
        "table",
        "markdown table",
        "html table",
        "generator",
        "data",
        "markdown",
        "html",
        "grid",
        "ascii table"
      ]
    },
    {
      "slug": "text-cleaner",
      "name": "Text Cleaner & Normalizer",
      "description": "Trim whitespace, remove duplicate lines, collapse spaces, and normalize text.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/text-cleaner/",
      "category": "text",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "text",
        "cleaner",
        "whitespace",
        "deduplicate",
        "formatter",
        "clean text",
        "remove duplicates",
        "trim spaces",
        "normalize",
        "dedup"
      ]
    },
    {
      "slug": "text-diff",
      "name": "Text Diff Comparator",
      "description": "Compare two pieces of text or code side-by-side with change summary.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/text-diff/",
      "category": "text",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "txt",
        "diff"
      ],
      "tags": [
        "diff",
        "compare",
        "text-diff",
        "code-diff",
        "lcs",
        "text diff",
        "code diff",
        "differences",
        "checker",
        "revision",
        "changes"
      ]
    },
    {
      "slug": "text-sorter",
      "name": "Text Line Sorter",
      "description": "Sort lines alphabetically, numerically, naturally, or in reverse with deduplication.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/text-sorter/",
      "category": "text",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "sort",
        "alphabetical",
        "lines",
        "natural-sort",
        "text",
        "alphabetize",
        "list sorter",
        "natural sort",
        "deduplicate"
      ]
    },
    {
      "slug": "unicode-lookup",
      "name": "Unicode Character Inspector",
      "description": "Inspect Unicode code points, UTF-8/UTF-16 encodings, and character names.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/unicode-lookup/",
      "category": "developer",
      "alsoIn": [
        "text"
      ],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "unicode",
        "code-point",
        "utf-8",
        "utf-16",
        "character-inspector",
        "codepoint",
        "ascii",
        "character",
        "symbol",
        "emoji"
      ]
    },
    {
      "slug": "unit-converter",
      "name": "Universal Unit Converter",
      "description": "Convert length, mass, temperature, area, volume, storage and speed.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/unit-converter/",
      "category": "math",
      "alsoIn": [
        "everyday"
      ],
      "processing": "local",
      "formats": [
        "txt"
      ],
      "tags": [
        "units",
        "converter",
        "metric",
        "imperial",
        "measurement",
        "unit converter",
        "length",
        "weight",
        "mass",
        "temperature",
        "storage",
        "speed"
      ]
    },
    {
      "slug": "timestamp-converter",
      "name": "Unix Timestamp Converter",
      "description": "Convert Unix timestamps to dates and convert dates to timestamps.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/timestamp-converter/",
      "category": "developer",
      "alsoIn": [
        "everyday"
      ],
      "processing": "local",
      "formats": [
        "txt"
      ],
      "tags": [
        "timestamp",
        "epoch",
        "datetime",
        "unix",
        "unix time",
        "converter",
        "iso8601",
        "utc",
        "clock"
      ]
    },
    {
      "slug": "url-parser",
      "name": "URL & Query String Parser",
      "description": "Break down URLs into protocol, host, path, hash, and structured query parameters.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/url-parser/",
      "category": "developer",
      "alsoIn": [
        "everyday"
      ],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "url",
        "parser",
        "query",
        "query-string",
        "uri",
        "query string",
        "parameters",
        "hostname",
        "pathname"
      ]
    },
    {
      "slug": "url-encoder",
      "name": "URL Encoder / Decoder",
      "description": "Encode or decode URLs, query parameters and URI components.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/url-encoder/",
      "category": "developer",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "txt"
      ],
      "tags": [
        "url",
        "encode",
        "decode",
        "uri",
        "percent-encoding",
        "encoder",
        "decoder",
        "percent encoding",
        "query string",
        "escape",
        "unescape"
      ]
    },
    {
      "slug": "uuid-generator",
      "name": "UUID Generator",
      "description": "Generate random (v4) or time-ordered (v7) UUIDs in bulk.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/uuid-generator/",
      "category": "developer",
      "alsoIn": [
        "security"
      ],
      "processing": "local",
      "formats": [
        "txt"
      ],
      "tags": [
        "uuid",
        "guid",
        "generator",
        "rfc9562",
        "unique id",
        "identifier",
        "rfc 9562",
        "rfc 4122",
        "random"
      ]
    },
    {
      "slug": "text-counter",
      "name": "Word & Character Counter",
      "description": "Count words, characters, sentences, lines and paragraphs as you type.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/text-counter/",
      "category": "text",
      "alsoIn": [
        "everyday",
        "education"
      ],
      "processing": "local",
      "formats": [
        "txt"
      ],
      "tags": [
        "text",
        "word-count",
        "character-count",
        "word counter",
        "character counter",
        "letters",
        "sentences",
        "paragraphs",
        "lines",
        "essay length"
      ]
    },
    {
      "slug": "word-frequency",
      "name": "Word Frequency Analyzer",
      "description": "Analyze word and phrase frequency, density, and rankings in any text.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/word-frequency/",
      "category": "text",
      "alsoIn": [],
      "processing": "local",
      "formats": [
        "text"
      ],
      "tags": [
        "word-frequency",
        "word-counter",
        "density",
        "text-analysis",
        "ranking",
        "frequency",
        "word count",
        "rankings",
        "analysis",
        "statistics"
      ]
    },
    {
      "slug": "xml-json",
      "name": "XML ↔ JSON Converter",
      "description": "Convert between XML and JSON documents bidirectionally in your browser.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/xml-json/",
      "category": "data",
      "alsoIn": [
        "developer"
      ],
      "processing": "local",
      "formats": [
        "xml",
        "json"
      ],
      "tags": [
        "xml",
        "json",
        "convert",
        "xml to json",
        "json to xml",
        "transform"
      ]
    },
    {
      "slug": "xml-formatter",
      "name": "XML Formatter & Minifier",
      "description": "Format, beautify and minify XML markup with syntax validation.",
      "url": "https://everything-free-by-quilonix.github.io/everything-free-tools/tools/xml-formatter/",
      "category": "developer",
      "alsoIn": [
        "data"
      ],
      "processing": "local",
      "formats": [
        "xml"
      ],
      "tags": [
        "xml",
        "formatter",
        "beautifier",
        "minify",
        "developer",
        "prettify",
        "indent"
      ]
    }
  ]
};
